version: "3.7"

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - ${MONGO_PORT}:27017
    backend:
        build: ./backend/
        container_name: backend
        restart: always
        environment:
            DB_HOST: ${DB_HOST}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
            DB_PORT: ${MONGO_PORT}
            PORT: ${BACKEND_PORT}
        ports:
            - ${BACKEND_PORT}:${BACKEND_PORT}
        depends_on:
            - mongodb
    frontend:
        build: ./frontend/
        container_name: frontend
        restart: always
        environment:
            INLINE_RUNTIME_CHUNK: ${INLINE_RUNTIME_CHUNK}
            NODE_ENV: ${NODE_ENV}
            PORT: ${PORT}
            NODE_VERSION: ${NODE_VERSION}
            REACT_APP_RECAPTCHA_SITE_KEY: ${REACT_APP_RECAPTCHA_SITE_KEY}
            REACT_APP_IPFS_GATEWAY: ${REACT_APP_IPFS_GATEWAY}
            SKIP_PREFLIGHT_CHECK: ${SKIP_PREFLIGHT_CHECK}
            REACT_APP_API_BASEPATH: ${REACT_APP_API_BASEPATH}
        ports:
            - 3000:3000
        depends_on:
            - backend
